### PR TITLE
Fix for the hostname resolution on Windows.

### LINKED ISSUE #196: Build Failure on Windows
I try to build GAPID on windows 10, but got build error like this:

[60/358] Linking Go executable test\test-core-os-device.exe
FAILED: test/test-core-os-device.exe
cmd.exe /C "cd . && "C:/Program Files/CMake/bin/cmake.exe" -DGO_ENV=C:/Users/zfk/gapid/release/go/goenv.cmake -DBUILDBOT=OFF -DGO_BUILD=test\test-core-os-device.exe -static   -DGO_PACKAGE=github.com/google/gapid/core/os/device -P D:/GoProjects/src/github.com/google/gapid/cmake/Modules/GoCompile.cmake && cmd.exe /C "cd /D D:\GoProjects\src\github.com\google\gapid\core\os\device && "C:\Program Files\CMake\bin\cmake.exe" -DTESTER=C:/Users/zfk/gapid/release/test/test-core-os-device.exe -DGO_PATH="D:/GoProjects/src/github.com/google/gapid/third_party;D:/GoProjects" -P D:/GoProjects/src/github.com/google/gapid/cmake/Modules/GoTest.cmake""
RAN: C:/Users/zfk/gapid/release/test/test-core-os-device.exe
GOT: --- FAIL: TestHost (0.34s)
        testing.go:37: 04:11:43.823 E: Error:Host.Name
                    Got       ``
                    Expect != ``
FAIL

CMake Error at D:/GoProjects/src/github.com/google/gapid/cmake/Modules/GoTest.cmake:25 (message):
  RESULT: 1

### PR DESCRIPTION
**Pull request by AWoloszyn**
Fixes #196.

### CODE REVIEW

File: core/os/device/deviceinfo/cc/windows/query.cpp [hunk 1]
```diff
@@ -97,13 +97,12 @@ bool createContext(void*) {
...
+    gContext.mOsVersion.dwOSVersionInfoSize = sizeof(gContext.mOsVersion);
     GetVersionEx((OSVERSIONINFO*)(&gContext.mOsVersion));
-    int major = osinfo.dwMajorVersion;
-    int minor = osinfo.dwMinorVersion;
-    int point = osinfo.dwBuildNumber;
-    bool isNTWorkstation = (osinfo.wProductType == VER_NT_WORKSTATION) ? 1 : 0;
+    int major = gContext.mOsVersion.dwMajorVersion;
+    int minor = gContext.mOsVersion.dwMinorVersion;
+    int point = gContext.mOsVersion.dwBuildNumber;
+    bool isNTWorkstation = (gContext.mOsVersion.wProductType == VER_NT_WORKSTATION) ? 1 : 0;
```
Comment (pmuetschard) [inline core/os/device/deviceinfo/cc/windows/query.cpp]: Drive by reviewer here.... Is the "? 1 : 0" needed?

Comment (AWoloszyn) [inline core/os/device/deviceinfo/cc/windows/query.cpp]: Nope, I can remove.

Comment (AWoloszyn) [inline core/os/device/deviceinfo/cc/windows/query.cpp]: Done
