### PR TITLE
Fixed export_replay to  work with ADB devices.

### LINKED ISSUE #2592: "gapit export_replay -originaldevice" crashes
Calling `gapit export_replay -originaldevice trace` causes the following crash.

$A0004

```
09:43:06.730 I: <gapis> 09:43:06.730 I: <gapis> Starting grpc server
09:43:07.001 I: <gapit> Loaded capture; id: 851cd184ad0f978c3d61a050c76598362c4f3c84
09:43:07.008 E: <gapis> panic: interface conversion: *bind.Simple is not adb.Device: missing method Command
09:43:07.008 E: <gapis> 
09:43:07.008 E: <gapis> goroutine 258 [running]:
09:43:07.008 E: <gapis> github.com/google/gapid/gapis/trace/android.NewTracer(0x71dc5e0, 0xc0025d4040, 0x0, 0x0)
09:43:07.008 E: <gapis> 	gapis/trace/android/trace.go:93 +0x55
09:43:07.008 E: <gapis> github.com/google/gapid/gapis/trace.(*Manager).createTracer(0xc000189c10, 0x7195560, 0xc0025a49c0, 0x71dc5e0, 0xc0025d4040)
09:43:07.008 E: <gapis> 	gapis/trace/manager.go:54 +0x30b
09:43:07.008 E: <gapis> github.com/google/gapid/gapis/trace.(*Manager).createTracer-fm(0x7195560, 0xc0025a49c0, 0x71dc5e0, 0xc0025d4040)
09:43:07.008 E: <gapis> 	gapis/trace/manager.go:44 +0x57
09:43:07.008 E: <gapis> github.com/google/gapid/core/os/device/bind.funcDeviceListener.OnDeviceAdded(0xc000189c20, 0xc000189c30, 0x7195560, 0xc0025a49c0, 0x71dc5e0, 0xc0025d4040)
09:43:07.008 E: <gapis> 	core/os/device/bind/registry.go:91 +0x5a
09:43:07.008 E: <gapis> github.com/google/gapid/core/os/device/bind.(*Registry).AddDevice(0xc0000647e0, 0x7195560, 0xc0025a4570, 0x71dc5e0, 0xc0025d4040)
09:43:07.008 E: <gapis> 	core/os/device/bind/registry.go:162 +0x44d
09:43:07.008 E: <gapis> github.com/google/gapid/gapis/server.exportReplay(0x7195560, 0xc0025a4570, 0xc0025a40f0, 0x0, 0xc00259a090, 0xd, 0xc0025d2040, 0x0, 0x0)
09:43:07.008 E: <gapis> 	gapis/server/export_replay.go:46 +0x1dde
09:43:07.008 E: <gapis> github.com/google/gapid/gapis/server.(*server).ExportReplay(0xc0002a0240, 0x7195560, 0xc0025a4570, 0xc0025a40f0, 0x0, 0xc00259a090, 0xd, 0xc0025d2040, 0x0, 0x0)
09:43:07.008 E: <gapis> 	gapis/server/server.go:288 +0x167
09:43:07.009 E: <gapis> github.com/google/gapid/gapis/server.(*grpcServer).ExportReplay(0xc0002a0280, 0x7195560, 0xc0025a4000, 0xc0025a6000, 0x0, 0x0, 0x0)
09:43:07.009 E: <gapis> 	gapis/server/grpc.go:458 +0x181
09:43:07.009 E: <gapis> github.com/google/gapid/gapis/service._Gapid_ExportReplay_Handler.func1(0x7195560, 0xc0025a4000, 0x6631c40, 0xc0025a6000, 0x0, 0x0, 0x0, 0x0)
09:43:07.009 E: <gapis> 	bazel-out/k8-dbg/bin/gapis/service/linux_amd64_debug/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10717 +0xfe
09:43:07.009 E: <gapis> github.com/google/gapid/core/app/auth.ServerInterceptor.func1(0x7195560, 0xc0025a4000, 0x6631c40, 0xc0025a6000, 0xc00259e180, 0xc00259e1a0, 0x0, 0x0, 0x0, 0x0)
09:43:07.009 E: <gapis> 	core/app/auth/auth.go:110 +0x28b
09:43:07.009 E: <gapis> github.com/google/gapid/gapis/service._Gapid_ExportReplay_Handler(0x68ca480, 0xc0002a0280, 0x7195560, 0xc0025a4000, 0xc000416000, 0xc0005181c0, 0x0, 0x0, 0x0, 0x0)
09:43:07.009 E: <gapis> 	bazel-out/k8-dbg/bin/gapis/service/linux_amd64_debug/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10719 +0x247
09:43:07.009 E: <gapis> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003e2f00, 0x71afa80, 0xc0003e3680, 0xc00037e400, 0xc0002dc840, 0xbfcb240, 0x0, 0x0, 0x0)
09:43:07.009 E: <gapis> 	external/org_golang_google_grpc/server.go:982 +0x1209
09:43:07.009 E: <gapis> google.golang.org/grpc.(*Server).handleStream(0xc0003e2f00, 0x71afa80, 0xc0003e3680, 0xc00037e400, 0x0)
09:43:07.009 E: <gapis> 	external/org_golang_google_grpc/server.go:1208 +0x981
09:43:07.009 E: <gapis> google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003bd760, 0xc0003e2f00, 0x71afa80, 0xc0003e3680, 0xc00037e400)
09:43:07.009 E: <gapis> 	external/org_golang_google_grpc/server.go:686 +0xb0
09:43:07.009 E: <gapis> created by google.golang.org/grpc.(*Server).serveStreams.func1
09:43:07.009 E: <gapis> 	external/org_golang_google_grpc/server.go:684 +0xa6
09:43:07.020 E: <gapit> rpc error: code = Unavailable desc = transport is closing
09:43:07.021 E: <gapit> Main failed
Error: Failed to export replay
   Cause: rpc error: code = Unavailable desc = transport is closing
```

### PR DESCRIPTION
**Pull request by AWoloszyn**
Our tracing system was trying to initialize the trace device
which is a mock device. This obviously won't work for a mock
device. Instead, make sure that the Mock devices are not allowed
to trace.

Fixed #2592

### CODE REVIEW

File: gapis/server/export_replay.go [hunk 1]
```diff
@@ -83,9 +92,9 @@ func exportReplay(ctx context.Context, c *path.Capture, d *path.Device, out stri
 						req.Attachment,        // api.FramebufferAttachment
 						fbInfo.Index,          // uint32
 						req.Settings.DrawMode, // service.DrawMode
-						true,                  // disableReplayOptimization bool
-						false,                 // displayToSurface bool
-						nil,                   // hints *service.UsageHints
+						true,  // disableReplayOptimization bool
```
Comment (hevrard) [inline gapis/server/export_replay.go]: Format looks broken here? (comments should be tabbed to align the ones of previous lines)
