### PR TITLE
Fixes for memory various memory requests

### LINKED ISSUE #914: gapic: UncheckedExecutionException in memory view
Not too sure how to reproduce. Seen when opening the memory tab.

```
com.google.common.util.concurrent.UncheckedExecutionException: com.google.gapid.server.Client$InternalServerErrorException: Pool size:65536 pool:2602 after:<capture:<id:<data:"\255\177\357\302\253&TP\271\375<y\"\273\212G=w8@" > > indices:7224 >  not found
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1326)
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1311)
	at com.google.gapid.views.MemoryView$FixedMemoryModel.getMemorySegment(MemoryView.java:887)
	at com.google.gapid.views.MemoryView$FixedMemoryModel.getReads(MemoryView.java:940)
	at com.google.gapid.views.MemoryView$MemoryPanel.paint(MemoryView.java:636)
	at com.google.gapid.widgets.InfiniteScrolledComposite.lambda$new$3(InfiniteScrolledComposite.java:73)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:154)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:59)
	at com.google.gapid.Main$UI$1.handleException(Main.java:89)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:109)
	at com.google.gapid.Main.main(Main.java:67)
Caused by: com.google.gapid.server.Client$InternalServerErrorException: Pool size:65536 pool:2602 after:<capture:<id:<data:"\255\177\357\302\253&TP\271\375<y\"\273\212G=w8@" > > indices:7224 >  not found
	at com.google.gapid.server.Client.throwIfError(Client.java:215)
	at com.google.gapid.server.Client.lambda$get$5(Client.java:91)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:461)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:440)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->get(memory { size: 65536 pool: 2602 after { capture { id { data: ad7fefc2ab265450b9fd3c7922bb8a473d773840 } } indices: 7224 } })
	at com.google.gapid.server.Client.get(Client.java:88)
	at com.google.gapid.views.MemoryView$State.lambda$createMemoryDataModel$1(MemoryView.java:396)
	at com.google.gapid.views.MemoryView$PagedMemoryDataModel.getPage(MemoryView.java:777)
	at com.google.gapid.views.MemoryView$PagedMemoryDataModel.get(MemoryView.java:747)
	at com.google.gapid.views.MemoryView$FixedMemoryModel.getMemorySegment(MemoryView.java:884)
	at com.google.gapid.views.MemoryView$FixedMemoryModel.getReads(MemoryView.java:940)
	at com.google.gapid.views.MemoryView$MemoryPanel.paint(MemoryView.java:636)
	at com.google.gapid.widgets.InfiniteScrolledComposite.lambda$new$3(InfiniteScrolledComposite.java:73)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.google.gapid.Main$UI.show(Main.java:109)
	at com.google.gapid.Main.main(Main.java:67)
```

### PR DESCRIPTION
**Pull request by pmuetschard**
- Return a DataUnavailable error when an invalid pool is requested
- Allow requesting of memory of a pool at the command that created the pool
- Fix the UI to handle errors when fetching memory

Fixes #914

### CODE REVIEW

File: gapis/memory/pool.go [hunk 1]
```diff
@@ -100,6 +111,49 @@ func (m *Pool) String() string {
...
+// Get returns the Pool with the given id.
+func (m *Pools) Get(id PoolID) (*Pool, error) {
+	if p, ok := m.pools[id]; ok {
+		return p, nil
+	}
+	return nil, fmt.Errorf("Pool %v not found", id)
+}
+
+// GetOrPanic returns the Pool with the given id, or panics if it's not found.
+func (m *Pools) GetOrPanic(id PoolID) *Pool {
```
Comment (ben-clayton) [inline gapis/memory/pool.go]: Argh. I really hate these functions - I'm trying to remove all panics from GAPIS as we keep on hitting them, but I do see that this is no worse than what we had before.
We typically call these sorts of abominations `MustXXX`, so this would be called `MustGet`.

File: gapis/memory/pool.go [hunk 2]
```diff
@@ -100,6 +111,49 @@ func (m *Pool) String() string {
 	return strings.Join(l, "\n")
 }
 
+// New creates and returns a new Pool and its id.
```
Comment (ben-clayton) [inline gapis/memory/pool.go]: `// NewPool...`
I think I actually prefer `New()` though, given that the type is `Pools`.

File: gapis/memory/pool.go [hunk 3]
```diff
@@ -41,12 +41,15 @@ type Pool struct {
 	OnWrite func(Range)
 }
 
-// Pools is a map of PoolID to *Pool.
-type Pools map[PoolID]*Pool
-
 // PoolID is an identifier of a Pool.
 type PoolID uint32
 
+// Pools is a map of PoolID to *Pool.
```
Comment (ben-clayton) [inline gapis/memory/pool.go]: Not really true now...

File: gapis/memory/pool.go [hunk 4]
```diff
@@ -145,6 +150,14 @@ func (m *Pools) Count() int {
 	return len(m.pools)
 }
 
+// SetOnCreate sets the OnCreate callback and invokes it for every pool already created.
+func (m *Pools) SetOnCreate(onCreate func(PoolID, *Pool)) {
```
Comment (ben-clayton) [inline gapis/memory/pool.go]: The `invokes it for every pool already created.` bit doesn't look used, so I'd recommend killing this function and just switch over to using the `OnCreate` field directly.

File: gapis/resolve/memory.go [hunk 5]
```diff
@@ -56,51 +74,31 @@ func Memory(ctx context.Context, p *path.Memory) (*service.Memory, error) {
...
 		requestSubCmdIdx := api.SubCmdIdx(fullCmdIdx)
 		syncedApi.MutateSubcommands(ctx, api.CmdID(cmdIdx), lastCmd, s,
 			func(s *api.State, subCommandIndex api.SubCmdIdx, cmd api.Cmd) {
 				// Turn on OnRead and OnWrite if the subcommand to be executed is or
 				// contained by the requested subcommand.
-				if requestSubCmdIdx.Equals(subCommandIndex) ||
-					requestSubCmdIdx.Contains(subCommandIndex) {
-					listenToReadWrite()
-				}
+				shouldRecord = requestSubCmdIdx.Contains(subCommandIndex)
```
Comment (ben-clayton) [inline gapis/resolve/memory.go]: You sure that `Contains` also covers the `Equals` case?
@Qining FYI.
