### PR TITLE
Switch to glslang

### LINKED ISSUE #348: GLSL parser: Cannot cope with parameter names sharing type names.
Given:

```C
struct Bar { int i; }; void Foo(Bar Bar) {}
```

You get the error:

```1:37: Unexpected token (Bar), was expecting one of: [, )]```

While I'm not entirely sure that this is legal GLSL, I've encountered captures that do this. We should support this case.

### LINKED ISSUE #415: Switch to glslang
Let's use the official reference compiler instead of our custom go one.

### LINKED ISSUE #539: uniform does not support struct in shader
Are we going to switch to glslang ?

Error (Unity shader):
Error during replay: "Failed to parse fragment shader source. Errors:
89:17: Unexpected token (o), was expecting one of: [{]
Declaration of 'o_Type' already exists in this scope.
89:18: Unexpected token (;), was expecting one of: [type struct]
90:1: Unexpected token (uniform), was expecting one of: []
90:14: Unexpected token (sampler2D), was expecting one of: [, ;]
102:10: Unexpected token ((), was expecting one of: [, ;]
105:5: Unexpected token (t10_1), was expecting one of: [type struct]
105:11: Unexpected token (=), was expecting one of: []
105:14: Unexpected token (tb0), was expecting one of: [, ;]
106:5: Unexpected token (t0), was expecting one of: [type struct]
106:7: Unexpected token (.), was expecting one of: []
107:5: Unexpected token (t0), was expecting one of: [type struct]
107:7: Unexpected token (.), was expecting one of: []
Undeclared identifier '_MainTex'.
108:5: Unexpected token (t16_2), was expecting one of: [type struct]
108:11: Unexpected token (=), was expecting one of: []
Declaration of 't0' already exists in this scope.
108:16: Unexpected token (*), was expecting one of: [, ;]
109:5: Unexpected token (t16_2), was expecting one of: [type struct]
109:10: Unexpected token (.), was expecting one of: []
110:5: Unexpected token (t16_3), was expecting one of: [type struct]
110:10: Unexpected token (.), was expecting one of: []
Declaration of 'xyz' already exists in this scope.
111:5: Unexpected token (SV_Target0), was expecting one of: [type struct]
111:15: Unexpected token (.), was expecting one of: []
Declaration of 'xyz' already exists in this scope.
112:5: Unexpected token (t0), was expecting one of: [type struct]
112:8: Unexpected token (=), was expecting one of: []
112:11: Unexpected token (abs), was expecting one of: [, ;]
113:5: Unexpected token (t0), was expecting one of: [type struct]
113:7: Unexpected token (.), was expecting one of: []
114:5: Unexpected token (t0), was expecting one of: [type struct]
114:7: Unexpected token (.), was expecting one of: []
115:5: Unexpected token (t0), was expecting one of: [type struct]
115:7: Unexpected token (.), was expecting one of: []
116:5: Unexpected token (t0), was expecting one of: [type struct]
116:7: Unexpected token (.), was expecting one of: []
Declaration of 'x' already exists in this scope.
117:5: Unexpected token (t0), was expecting one of: [type struct]
117:7: Unexpected token (.), was expecting one of: []
Declaration of 'x' already exists in this scope.
118:5: Unexpected token (t0), was expecting one of: [type struct]
118:7: Unexpected token (.), was expecting one of: []
Declaration of 'x' already exists in this scope.
119:5: Unexpected token (SV_Target0), was expecting one of: [type struct]
119:15: Unexpected token (.), was expecting one of: []
Declaration of 'w' already exists in this scope.
120:5: Unexpected token (return), was expecting one of: [type struct]
120:11: Unexpected token (;), was expecting one of: []
121:2: Unexpected token (<nil>), was expecting one of: [, ;]
Source:
  1: #version 300 es
  2: precision highp float;
  3: precision highp int;
  4: struct o_Type {
  5: 	vec4 vertex;
  6: 	mediump vec4 color;
  7: 	vec2 texcoord;
  8: 	vec4 worldPos;
  9: 	lowp float grey;
 10: };
 11: uniform 	vec4 _Time;
 12: uniform 	vec4 _SinTime;
 13: uniform 	vec4 _CosTime;
 14: uniform 	vec4 unity_DeltaTime;
 15: uniform 	vec3 _WorldSpaceCameraPos;
 16: uniform 	vec4 _ProjectionParams;
 17: uniform 	vec4 _ScreenParams;
 18: uniform 	vec4 _ZBufferParams;
 19: uniform 	vec4 unity_OrthoParams;
 20: uniform 	vec4 unity_CameraWorldClipPlanes[6];
 21: uniform 	mat4 unity_CameraProjection;
 22: uniform 	mat4 unity_CameraInvProjection;
 23: uniform 	vec4 _WorldSpaceLightPos0;
 24: uniform 	vec4 _LightPositionRange;
 25: uniform 	vec4 unity_4LightPosX0;
 26: uniform 	vec4 unity_4LightPosY0;
 27: uniform 	vec4 unity_4LightPosZ0;
 28: uniform 	mediump vec4 unity_4LightAtten0;
 29: uniform 	mediump vec4 unity_LightColor[8];
 30: uniform 	vec4 unity_LightPosition[8];
 31: uniform 	mediump vec4 unity_LightAtten[8];
 32: uniform 	vec4 unity_SpotDirection[8];
 33: uniform 	mediump vec4 unity_SHAr;
 34: uniform 	mediump vec4 unity_SHAg;
 35: uniform 	mediump vec4 unity_SHAb;
 36: uniform 	mediump vec4 unity_SHBr;
 37: uniform 	mediump vec4 unity_SHBg;
 38: uniform 	mediump vec4 unity_SHBb;
 39: uniform 	mediump vec4 unity_SHC;
 40: uniform 	mediump vec3 unity_LightColor0;
 41: uniform 	mediump vec3 unity_LightColor1;
 42: uniform 	mediump vec3 unity_LightColor2;
 43: uniform 	mediump vec3 unity_LightColor3;
 44: uniform 	vec4 unity_ShadowSplitSpheres[4];
 45: uniform 	vec4 unity_ShadowSplitSqRadii;
 46: uniform 	vec4 unity_LightShadowBias;
 47: uniform 	vec4 _LightSplitsNear;
 48: uniform 	vec4 _LightSplitsFar;
 49: uniform 	mat4 unity_World2Shadow[4];
 50: uniform 	mediump vec4 _LightShadowData;
 51: uniform 	vec4 unity_ShadowFadeCenterAndType;
 52: uniform 	mat4 glstate_matrix_mvp;
 53: uniform 	mat4 glstate_matrix_modelview0;
 54: uniform 	mat4 glstate_matrix_invtrans_modelview0;
 55: uniform 	mat4 _Object2World;
 56: uniform 	mat4 _World2Object;
 57: uniform 	vec4 unity_LODFade;
 58: uniform 	vec4 unity_WorldTransformParams;
 59: uniform 	mat4 glstate_matrix_transpose_modelview0;
 60: uniform 	mat4 glstate_matrix_projection;
 61: uniform 	lowp vec4 glstate_lightmodel_ambient;
 62: uniform 	mat4 unity_MatrixV;
 63: uniform 	mat4 unity_MatrixVP;
 64: uniform 	lowp vec4 unity_AmbientSky;
 65: uniform 	lowp vec4 unity_AmbientEquator;
 66: uniform 	lowp vec4 unity_AmbientGround;
 67: uniform 	lowp vec4 unity_FogColor;
 68: uniform 	vec4 unity_FogParams;
 69: uniform 	vec4 unity_LightmapST;
 70: uniform 	vec4 unity_DynamicLightmapST;
 71: uniform 	vec4 unity_SpecCube0_BoxMax;
 72: uniform 	vec4 unity_SpecCube0_BoxMin;
 73: uniform 	vec4 unity_SpecCube0_ProbePosition;
 74: uniform 	mediump vec4 unity_SpecCube0_HDR;
 75: uniform 	vec4 unity_SpecCube1_BoxMax;
 76: uniform 	vec4 unity_SpecCube1_BoxMin;
 77: uniform 	vec4 unity_SpecCube1_ProbePosition;
 78: uniform 	mediump vec4 unity_SpecCube1_HDR;
 79: uniform 	lowp vec4 unity_ColorSpaceGrey;
 80: uniform 	lowp vec4 unity_ColorSpaceDouble;
 81: uniform 	mediump vec4 unity_ColorSpaceDielectricSpec;
 82: uniform 	mediump vec4 unity_ColorSpaceLuminance;
 83: uniform 	mediump vec4 unity_Lightmap_HDR;
 84: uniform 	mediump vec4 unity_DynamicLightmap_HDR;
 85: uniform 	vec4 _ClipRange0;
 86: uniform 	vec4 _ClipArgs0;
 87: uniform 	vec4 _ClipRange1;
 88: uniform 	vec4 _ClipArgs1;
 89: uniform 	o_Type o;
 90: uniform lowp sampler2D _MainTex;
 91: uniform lowp sampler2D _AlphaTex;
 92: in mediump vec4 vs_COLOR0;
 93: in highp vec2 vs_TEXCOORD0;
 94: in lowp float vs_TEXCOORD2;
 95: in highp vec4 vs_TEXCOORD1;
 96: layout(location = 0) out mediump vec4 SV_Target0;
 97: highp vec4 t0;
 98: bool tb0;
 99: lowp float t10_1;
100: mediump vec4 t16_2;
101: mediump vec3 t16_3;
102: void main()
103: {
104:     tb0 = 0.0>=vs_TEXCOORD2;
105:     t10_1 = (tb0) ? 1.0 : 0.0;
106:     t0.w = texture(_AlphaTex, vs_TEXCOORD0.xy).w;
107:     t0.xyz = texture(_MainTex, vs_TEXCOORD0.xy).xyz;
108:     t16_2 = t0 * vs_COLOR0;
109:     t16_2.x = dot(t16_2.xyz, vec3(0.298999995, 0.587000012, 0.114));
110:     t16_3.xyz = t0.xyz * vs_COLOR0.xyz + (-t16_2.xxx);
111:     SV_Target0.xyz = vec3(t10_1) * t16_3.xyz + t16_2.xxx;
112:     t0 = -abs(vs_TEXCOORD1) + vec4(1.0, 1.0, 1.0, 1.0);
113:     t0.xy = t0.xy * _ClipArgs0.xy;
114:     t0.zw = vec2(t0.z * _ClipArgs1.x, t0.w * _ClipArgs1.y);
115:     t0.xz = min(t0.yw, t0.xz);
116:     t0.x = min(t0.z, t0.x);
117:     t0.x = clamp(t0.x, 0.0, 1.0);
118:     t0.x = t0.x * t16_2.w;
119:     SV_Target0.w = t0.x;
120:     return;
121: }"

### PR DESCRIPTION
**Pull request by dsrbecky**
Closes #415
Closes #539
Closes #348

### CODE REVIEW

File: cmd/shadertool/main.go [hunk 1]
```diff
@@ -43,30 +46,43 @@ func run(ctx context.Context) error {
...
+			// Process the shader
+			result, err := convert(string(source), filepath.Ext(input))
+			if err != nil {
+				fmt.Printf("%v: %v\n", input, err)
+				return
+			}
+
+			// Write output
+			if *out == "" {
+				fmt.Print(result)
```
Comment (ben-clayton) [inline cmd/shadertool/main.go]: Nit: not great to be printing the output of multiple shaders concurrently, but I guess this is just a debug tool.

**Comment by dsrbecky** [comment]
(added two more commits)

File: gapis/shadertools/cc/spv_manager.cpp [hunk 2]
```diff
@@ -95,6 +95,23 @@ void SpvManager::mapDeclarationNames(std::string name_pref) {
   }
 }
 
+// Replace the build-in gl_ViewID_OVR with custom uniform.
```
Comment (ben-clayton) [inline gapis/shadertools/cc/spv_manager.cpp]: nit: built-in
