### PR TITLE
Counter Fixes/Enhancements

### LINKED ISSUE #3687: GPU Frequency is inverted
**Environment information:**
 - GAPID version: 1.7.0-dev-20200109
 - Host OS: Windows
 If tracing on Android:
 - Device model: Exynos 9825
 - Android Version: 10

**Bug description**
The `power/gpu_frequency` rendering in GAPID is inverted

**Reproduction steps**
 * [trace.perfetto.gz](https://github.com/google/gapid/files/4104518/trace.perfetto.gz)
 * Open trace in `ui.perfetto.dev`
 * Open trace in GAPID
 * GAPID seems to have the `gpufreq` GPU counter inverted

**Screenshots**

perfetto-gpu-frequency-ui
perfetto-gpu-frequency-gapid

### PR DESCRIPTION
**Pull request by pmuetschard**
- Highlight the hovered sample to make it more clear that it is a bar graph.
- Put the tooltip in a better location when the counter sample is small enough, so that it doesn't obstruct the sample
- Distinguish delta vs event based counters.
- Give the GPU frequency counter a better display name.

Fixes #3687 
Bug: http://b/147757073
Bug: http://b/142074736

### CODE REVIEW

File: gapic/src/main/com/google/gapid/perfetto/views/CounterPanel.java [hunk 1]
```diff
@@ -250,5 +257,10 @@ public HoverCard(
       this.size = new Size(leftWidth + HOVER_PADDING + rightLabel + Math.max(minSize.w, maxSize.w),
           Math.max(valueSize.h + avgSize.h, minSize.h + maxSize.h) + HOVER_PADDING);
     }
+
+    public double getTooltipX() {
+      // If the tooltip is smaller than the sample, show it after the sample.
+      return ((size.w < endX - startX) ? mouseX + CURSOR_SIZE / 2 : endX) + HOVER_MARGIN;
```
Comment (stellama0208) [inline gapic/src/main/com/google/gapid/perfetto/views/CounterPanel.java]: Puzzle: The code to me looks more like: "If the tooltip is smaller than the sample, show it after the mouse; If the tooltip is larger than the sample, show it after the sample.", which is opposite from the above comment.

File: gapic/src/main/com/google/gapid/perfetto/models/CounterInfo.java [hunk 2]
```diff
@@ -188,4 +190,16 @@ public static Type of(String string) {
...
     }
   }
+
+  public static enum Interpolation {
+    Delta, // the value represents the counter "amount" since the last sample.
+    Event; // the value represents the current value until the next sample.
+
+    public static Interpolation of(QueryEngine.Row row) {
+      // Only GPU counters, and not the gpufreq counter, are Delta counters.
+      // TODO: this should be part of the counter definition in the backend.
```
Comment (lpy) [inline gapic/src/main/com/google/gapid/perfetto/models/CounterInfo.java]: Could you please file a bug and add the id here?

Comment (pmuetschard) [reply gapic/src/main/com/google/gapid/perfetto/models/CounterInfo.java]: Oops, missed this before submitting. Filed bug: http://b/148458673
