### PR TITLE
Search/Filter for activity chooser and other fixes

### LINKED ISSUE #181: The Select Activity for capture dialog needs search
There is a lot of applications available on rooted phone.
It would be nice to be able to search thought the list.

### PR DESCRIPTION
**Pull request by pmuetschard**
Closes #181

### CODE REVIEW

File: gapic/src/main/com/google/gapid/views/ActivityPickerDialog.java [hunk 1]
```diff
@@ -171,67 +263,111 @@ protected void showError(String message) {
...
+    }
+
+    @Override
+    public StyledString getStyledText(Object element) {
+      if (element instanceof PkgInfo.Package) {
+        return new StyledString(((PkgInfo.Package)element).getName());
+      } else if (element instanceof PkgInfo.Activity) {
+        PkgInfo.Activity a = (PkgInfo.Activity)element;
+        return new StyledString(
+            a.getName(), Action.findLaunchAction(a) != null ? theme.labelStyler() : null);
```
Comment (ben-clayton) [inline gapic/src/main/com/google/gapid/views/ActivityPickerDialog.java]: Does `theme.labelStyler()` make the text bold? If so, this is really not clear.

Comment (pmuetschard) [inline gapic/src/main/com/google/gapid/views/ActivityPickerDialog.java]: It styles it as a label, which does mean bold. The name of the styler is not the best, it probably should be called em(phasized)Styler.
