### PR TITLE
Automatically unlock device screen when possible

### LINKED ISSUE #2747: Tracing Failed   Cause: Could not start trace   Cause: Cannot trace app on locked device
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: mac os x x86_64 device: HUAWEI P30

com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Cannot trace app on locked device
	at com.google.gapid.server.Client.throwIfError(Client.java:301)
	at com.google.gapid.server.Client.lambda$streamTrace$49(Client.java:275)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:217)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:272)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:132)
	at com.google.gapid.MainWindow.lambda$updateFileMenu$11(MainWindow.java:255)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:399)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)

### PR DESCRIPTION
**Pull request by hevrard**
This is a refactor of the device screen unlock logic, to simplify it down to two functions:

- UnlockScreen() which tries to get the screen on and unlocked

- IsScreenUnlocked() which returns true if the screen is on and unlocked

When the screen cannot be automatically unlocked, the new error message clearly tells the user to unlock the device screen.

Along the way, this removes the feature of putting back the screen off if it was off before tracing. I argue this was hardly desirable in any case.

Fixes #2747

### CODE REVIEW

**Comment by hevrard** [comment]
Arguably fix #2747

File: gapis/perfetto/android/trace.go [hunk 1]
```diff
@@ -54,18 +54,18 @@ func Start(ctx context.Context, d adb.Device, a *android.ActivityAction, opts *s
 		}.Bind(ctx)
 	}
 
-	log.I(ctx, "Turning device screen on")
-	if err := d.TurnScreenOn(ctx); err != nil {
-		return nil, log.Err(ctx, err, "Couldn't turn device screen on")
+	log.I(ctx, "Unlock device screen")
```
Comment (pmuetschard) [inline gapis/perfetto/android/trace.go]: "Unlocking..."

File: gapii/client/adb.go [hunk 2]
```diff
@@ -77,18 +77,18 @@ func Start(ctx context.Context, p *android.InstalledPackage, a *android.Activity
 
 	ctx = log.V{"abi": abi.Name}.Bind(ctx)
 
-	log.I(ctx, "Turning device screen on")
-	if err := d.TurnScreenOn(ctx); err != nil {
-		return nil, nil, log.Err(ctx, err, "Couldn't turn device screen on")
+	log.I(ctx, "Unlock device screen")
```
Comment (pmuetschard) [inline gapii/client/adb.go]: "Unlocking..."

File: core/os/android/adb/screen.go [hunk 3]
```diff
@@ -17,71 +17,94 @@ package adb
...
 
-// TurnScreenOff turns the device's screen off.
-func (b *binding) TurnScreenOff(ctx context.Context) error {
-	if isOn, err := b.IsScreenOn(ctx); err != nil || !isOn {
-		return err
-	}
-	return b.KeyEvent(ctx, android.KeyCode_Power)
-}
+// UnlockScreen tries to make the device's screen to be on and unlocked.
+func (b *binding) UnlockScreen(ctx context.Context) error {
```
Comment (pmuetschard) [inline core/os/android/adb/screen.go]: I think it makes sense to return an error when the screen is not in the `screenOnUnlocked` state after this call. That way we don't have to follow the `UnlockScreen`  then check `IsScreenUnlocked` pattern. If we want callers to be able to distinguish between the "i tried, it didn't work" error and other errors, you can make the returned error a public constants (like, say, `io.EOF` et al)

File: gapis/perfetto/android/trace.go (hunk 1 above)
Comment (hevrard) [reply gapis/perfetto/android/trace.go]: done

File: gapii/client/adb.go (hunk 2 above)
Comment (hevrard) [reply gapii/client/adb.go]: done

File: core/os/android/adb/screen.go (hunk 3 above)
Comment (hevrard) [reply core/os/android/adb/screen.go]: Good point, I adapted this way: UnlockScreen() now returns (bool, error) to indicate whether is successfully managed to unlock the screen.
