### PR TITLE
Fix indices for subcommand in Vulkan when resolving command groups

### LINKED ISSUE #1214: Vulkan Command Tree Grouping Returns Wrong Command paths.
Given a trace with the following tree:
```
- Frame 1 (0-363)
- Frame 2 (364-372)
  - Draw 1 (364-371)
    - 364: vkWaitForFences
    - ...
    - 371: vkQueueSubmit
      - [371 0]
        - [371 0 0]
          - RenderPass
            - 371.0.0.0: vkCmdBeginRenderPass
            - ...
            - 371.0.0.6: vkCmdEndRenderPass
  - vkQueuePresnetKHR
```

When fetching the nodes from the server the following values are returned:

The node at `[1, 0, 7]` (vkQueueSubmit) is for command: `[371]` - Correct.
The node at `[1, 0, 7, 0]` is for command: `[371, 0, 0]` - Should be `[371, 0]`.
The node at `[1, 0, 7, 0, 0]` is for command `[371, 0, 0, 0]` - Should be `[371, 0, 0]`.
The node at `[1, 0, 7, 0, 0, 0]` (RenderPass) is for commands `[0]-[6]`- Should be `[371, 0, 0]`.
The nodes at `[1, 0, 7, 0, 0, 0, x]` are for commands `[371, 0, 0, x]`, which is correct again.

This results in strange behavior, especially when selecting the RenderPass node.

### PR DESCRIPTION
**Pull request by Qining**
Should fix #1214

Turns out we just need to remove two historical lines of code

### CODE REVIEW

File: gapis/resolve/command_tree.go [hunk 1]
```diff
@@ -118,8 +118,6 @@ func CommandTreeNode(ctx context.Context, c *path.CommandTreeNode) (*service.Com
 		commandEnd := append([]uint64{}, item.Id...)
```
Comment (ben-clayton) [inline gapis/resolve/command_tree.go]: Do we need these now? Can't we just use item.Id where ever these were used?
